---
framework: mocha
preRun:
  command:
    - npm install
preMerge:
  pattern:
    - "./**/*.spec.js"
postMerge:
  pattern: 
    - "./**/*.spec.js"
postRun:
  command:
    - node --version
tier: medium
version: 1.1
